name: Github Actions
on:
  push:
jobs:
  italian-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - run: sudo apt update
      - run: pwd
      - run: ls -la
      - run: java -version
      - run: cd Azienda
      - run: ls
      - run: pwd
        working-directory: Azienda
      - run: mvn install
        working-directory: Azienda
